### PR TITLE
rewrite for 4.4 kernel

### PR DESCRIPTION
**Pull request by fivdi**
This PR is a rewrite of BeagleBone-IO for the Linux 4.4 kernel. It was tested with `Debian 8.6 2016-11-06 4GB SD LXQT`, which can be downloaded [here](https://beagleboard.org/latest-images). This image comes with Node.js v0.12.17 preinstalled. The PR can be installed with `npm install fivdi/beaglebone-io#rewrite` and should work wth Node.js v0.12, v4, v6 and v7.

### CODE REVIEW

**Comment by julianduque** [comment]
This is looking great!! I'll start testing on my BBB (lately I've been having issues flashing new images)

**Comment by fivdi** [comment]
@julianduque 

> This is looking great!!

Thanks. I'm still working on the tests and it will take a while before they're finished.

> I'll start testing on my BBB

Excellent. That would be good. To the best of my knowledge, everything should function correctly. Please note the changes to the [pin mappings](https://github.com/fivdi/beaglebone-io/tree/rewrite#pin-mappings). The [Arduino pin mappings](https://github.com/julianduque/beaglebone-io#pin-mappings) are no longer available.

> lately I've been having issues flashing new images

Perhaps we are seeing the exact same issue. I can't flash the [latest images](https://beagleboard.org/latest-images) which are `Debian 8.7 2017-03-19 4GB SD LXQT` and `Debian 8.7 2017-03-19 4GB SD IoT`. I can however flash the slightly older images `Debian 8.6 2016-11-06 4GB SD LXQT` and `Debian 8.6 2016-12-09 4GB SD IoT` which are still available for download. With `Debian 8.6 2016-12-09 4GB SD IoT` I had [this issue](https://github.com/beagleboard/bb.org-overlays/issues/41) and had to `sudo apt update ; sudo apt upgrade`. Perhaps @RobertCNelson knows why the latest images can't be flashed. On my BeagleBone Black, the boot messages that can be seen over the serial port complain about partition 2 not being present.

**Comment by RobertCNelson** [comment]
@fivdi sounds like an old bootloader in eMMC... Does it help if you push the "boot" button before power-on?

Regards,

**Comment by julianduque** [comment]
@RobertCNelson "boot" button before power-on keeps two leds blinking after a while (USR0 and USR1).

I edited the uEnv.txt file to flash with the other alternative and it seems it flashes, but, after booting without the sd card it got stuck with two leds on.

**Comment by fivdi** [comment]
@RobertCNelson 

> sounds like an old bootloader in eMMC... Does it help if you push the "boot" button before power-on?

Yes, pushing the boot button before power-on solves the problem for me. Thanks for the help for the nth time :)

@julianduque I'm booting from the SD card not from eMMC. May you should take a look at the output on the [serial port](http://mysticengineering.com/debug.buddy/images/beaglebone-black-serial.jpg) during boot to see what it says.

**Comment by fivdi** [comment]
The first post above contains the the text WIP but I'm about to remove it. I think the PR is now ready for a review.

There are a number of points about the PR worth mentioning that may need further discussion.

 * The I2C test were removed as there is no longer any code in BeagleBone-IO related to I2C. BeagleBone inherits from [LinuxIO](https://github.com/fivdi/linux-io) which contains the I2C code.
 * The tests in not-implemented.js have been deactivated as the function that are expected to throw errors no longer throw errors.
 * Support for Arduino pin numbering has been dropped.
 * Functions digitalWrite/digitalRead etc no longer call pinMode to set the pin to the appropriate mode. J5 doesn't appear to need this.
 * The mode of a pin can't be changed. I may be mistaken here but I don't think that the current version of BeagleBone-IO supports this correctly either.

The README needs to be updated to explain what has changed. That can be done after the review.

**Comment by fivdi** [comment]
The [readme](https://github.com/fivdi/beaglebone-io/blob/rewrite/README.md) has been updated and includes a migration guide.

**Comment by julianduque** [comment]
@fivdi migration guide and readme looks perfect, I'm good with merging this PR now, or if you prefer @MrYsLab to have a quick peak we can wait

**Comment by fivdi** [comment]
I don't know when @MrYsLab will be available. I'd say go ahead and merge.

**Comment by julianduque** [comment]
🎉

**Pull request merged**
